Settings:
   MOTD: "&6&n=->&eAngloCraft&6&n<-=" #Sets the server list MOTD - '&' supported
   MaxPlayers: 9999 #Sets the default max players for when no players are online
   Scramble_Chat: "true" #Enables/Disables the scrambling of chat
   Chat_Distance: 30 #Sets the distance players can talk in
   Proximity_Chat: "true" #Enables/Disables proximity chat
   Character_Creation: 
      NPC_Name: "&3&lGideon" #Sets the required name of the character creation NPC (Only if Citizens is enabled)
      Saxon_NPC: "&6&lPriest"
      Dane_NPC: "&6&lSeer"
      Saxon_Item: "iron_sword"
      Dane_Item: "iron_axe"
      Saxon_Item_Name: "&e&lSaxons"
      Dane_Item_Name: "&e&lDanes"
   GUI_Titles:
      Faction_Select: "&2&lChoose your faction..."